### PR TITLE
dashboard setup

### PR DESCRIPTION
**Pull request by Tardigrade180**
added the new dashboard

### CODE REVIEW

**Review by Faizawahab — APPROVED** [review]
Reviewed

**Review by odeifuo44 — APPROVED** [review]
great job

**Review by Tardigrade180 — COMMENTED** [review]
okay

**Review by Faizawahab — APPROVED** [review]

**Review by Faizawahab — APPROVED** [review]
okay

**Review by Faizawahab — APPROVED** [review]
okay

**Pull request merged**
